version: '3'

services:

  influxdb:
    image: influxdb:latest
    user: $GID:$UID
    ports:
      - 8086:8086
    volumes:
      - ./data/influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    user: $GID:$UID
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - influxdb
